trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  condition: succeeded()
  displayName: 'Copy BlogBuilder to artifact directory'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/BlogToHtml/bin/$(buildConfiguration)/netcoreapp3.1/'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/BlogToHtml'

- task: CopyFiles@2
  condition: succeeded()
  displayName: 'Copy Content files to artifact directory'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/Content/'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/Content'

- task: PublishBuildArtifacts@1
  condition: succeeded()
  displayName: 'Pushlish BlogBuilder artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/BlogToHtml'
    artifactName: 'BlogToHtml'
    
- task: PublishBuildArtifacts@1
  condition: succeeded()
  displayName: 'Pushlish Content artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Content'
    artifactName: 'Content'
