trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  condititon: succeeded()
  displayName: 'Execute generator'
  workingDirectory: '$(Build.SourcesDirectory)/BlogToHtml/bin/$(buildConfiguration)/netcoreapp3.1/'
  targetType: 'inline'
  script: 
    & BlogToHtml.exe -c "$(Build.SourcesDirectory)\Content" -o "$(Build.SourcesDirectory)\Output" -x True

- task: CopyFiles@2
  condition: succeeded()
  displayName: 'Copy Generated files to artifact directory'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/Output/'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/Output'

- task: PublishBuildArtifacts@1
  condition: succeeded()
  displayName: 'Pushlish Generated output artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Output'
    artifactName: 'Blog'