trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


stages:
- stage: Build
  jobs:
    - job: Restore Nuget Packages
      steps:
      - task: NuGetToolInstaller@1
      
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

    - job: Build solution
      steps:
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

- stage: Generate
  jobs:
  - job: Use powershell to execute blog generator
    condition: succeeded()
    steps:
    - pwsh: |
      cd $(Build.SourcesDirectory)/BlogToHtml/bin/$(buildConfiguration)/netcoreapp3.1/
      BlogToHtml.exe -c "$(Build.SourcesDirectory)/Content" -o "$(Build.SourcesDirectory)/Output" -x True

- stage: Publish
  jobs:
  - job: Copy and publish
    condition: succeeded()
    steps:    
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)/Output/'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)/Output'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/Output'
        artifactName: 'Blog'