trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- task: NuGetToolInstaller@1
      
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  condition: succeeded()
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2 
  condition: succeeded()
  inputs:
    targetType: inline
    workingDirectory: '$(Build.SourcesDirectory)/BlogToHtml/bin/$(buildConfiguration)/netcoreapp3.1/'
    script: |
      &BlogToHtml -c "$(Build.SourcesDirectory)/Content" -o "$(Build.SourcesDirectory)/Output" -x True

- task: CopyFiles@2
  condition: succeeded()
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/Output/'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/Output'
    
- task: PublishBuildArtifacts@1
  condition: succeeded()
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Output'
    artifactName: 'Blog'