trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


stages:
- stage: Build
  jobs:
    - job: RestorePackages
      steps:
      - task: NuGetToolInstaller@1
      
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

    - job: BuildSolution
      condition: succeeded()
      steps:
      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

    - job: GenerateBlog
      condition: succeeded()
      steps:
      - pwsh: |
           cd $(Build.SourcesDirectory)/BlogToHtml/bin/$(buildConfiguration)/netcoreapp3.1/
           BlogToHtml.exe -c "$(Build.SourcesDirectory)/Content" -o "$(Build.SourcesDirectory)/Output" -x True


    - job: CopyAndPublish
      condition: succeeded()
      steps:    
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/Output/'
          contents: '**'
          targetFolder: '$(Build.ArtifactStagingDirectory)/Output'
    
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)/Output'
          artifactName: 'Blog'