trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  - group: SharedVariables
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

steps:
- task: NuGetToolInstaller@1
      
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  condition: succeeded()
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2 
  condition: succeeded()
  inputs:
    targetType: inline
    workingDirectory: '$(Build.SourcesDirectory)/BlogToHtml/bin/$(buildConfiguration)/netcoreapp3.1/'
    script: |
      write-host "current directory = $(get-location)"
      & .\BlogToHtml.exe -c "$(Build.SourcesDirectory)/Content" -o "$(Build.SourcesDirectory)/Output" -x True

- task: PowerShell@2 
  displayName: Clone existing GitHub repository
  condition: succeeded()
  inputs:
    targetType: inline
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    script: |
      write-host "current directory = $(get-location)"
      md -Force 'SiteSource'
      git clone https://LeeSanderson:$(Variables.GitHubAccessToken)@github.com/LeeSanderson/Blog.git --branch=main . --quiet
      if ($lastexitcode -gt 0)
      {
        write-host "Clone failed - check GitHubAccessToken is valid. Error code $lastexitcode"
      }
      


- task: CopyFiles@2
  condition: succeeded()
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/Output/'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/Output'
    
- task: PublishBuildArtifacts@1
  condition: succeeded()
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Output'
    artifactName: 'Blog'