trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  - group: SharedVariables
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

steps:
- task: NuGetToolInstaller@1
      
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  condition: succeeded()
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  condition: succeeded()
  inputs:
    testAssemblyVer2: |
      **\bin\**\BlogToHtml.UnitTests.dll
    codeCoverageEnabled: True     
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishPipelineArtifact@1
  displayName: Publish Blog Generator Artifact 
  condition: succeeded()
  inputs:
    targetPath: '$(Build.SourcesDirectory)/BlogToHtml/bin/$(buildConfiguration)/net6/'
    artifactName: 'blogToHtml'